sudo: false
language: node_js
node_js:
- '4.1'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
  - secure: kDpsk1p4oevXXxt/bOTnO2GHgu3K+u+b+GNzjHMucihvV8Mm54KmNTG1OTXUUtP1E2ZawxICL71dQpkVFf1Gs2ZyJgnopKU5bP7ix647wGQSw+38O4zcWgTLkEY7oQM8tL0DdcvwiqbX4X6Hjt+CuH8ElRw66xegboQUykqR0mAxJQA9ACGOLwWFwMnb4TPaV6GuKkMr7TWr+r2WgjJ0O+k3p4NZM9249H47rmL07razXjG4KOU4qZfVbrNuLRMdEjSGyd5WTIGZ1zqG6PBeouR/ofQG5v8TZfRsoXKHwEk6C72vZAg2FAv6KeggNhmIXpIqOH4oVgGi6ZGdeM2NKeLjvDRi4kArbfhLUNNHIycj5WHuUqvCTgkUmAaWarVFxcMxtgftU3D0E2mkjOfImPHik7DwHznjSO+iCnEQJYpEOnSUiYOy76v/dW9mzA1RxXCwvFC0erJeZjvuisGL4hU3XfdaczvIN4bhSQj/SaiCIlFQghA7E/fRCCu8WcRahBj/c517WtxIPn1gOAo56imxiwF/NBKykaQa3yv6fj40/O8B6kf29GoQSW2wl+u+KQ0N7o2TiVi2200Dvl8GsonOrGid+scyRkdJfRj4fgTBhgDRQA+DAKCOw/FQUuc1XvkOG/8X7m6dC9lcfq+Fltvkt4fV191d5bONP59O/FM=
