sudo: false
language: node_js
node_js:
- '4.1'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
  - secure: wuXgLJM7cVvM2i7ETuwobTbqWMThpINJ0CP8Ihm2CI2GE0dD/tpKV+anNB9a0gTIFXYWy/Fc/4Fzm6JTe9XH0SO72AaTOM0hVpnjSd5Ee/FRjmGCtm/oIydowWtWYQ3PdpKsC5UuPIx64+jaoZYuIeOhMVYENAjSd2AgUvnQUwrgZInI3KiKlPBv6JPrm0WjZE2q1R2dWjzbzDnTTag/jdqSkYcsndYOef+pJ0ngtgXqjgFQJ2M3MJY9Bx+/5OlvTRGSn9e229uppd2m5iBRHjBM/1C7rGYipq8WX4WKSL/mzieDZk/4ligh1dI/dnBalSb49SklpJC+CoMT2a5Ucq5FsyAhFm5ikbXTujwO4ZDMlDSCWTbXHN1fUp3lNVrwjg8u7vCzl5Ccg5y07nTNQUkL5WQzviNNX0fqJdY8gg/sP/klM3wqP+HMemb3tv9mfi0LWrkxBqohhItLs8fDtEMtUgocB0taYRF6Iey6TH9a3JOtUuIYJvAtsRerbz5c1NZ35Bqp1+pzydgLv2vDQgEN1MoUQZrxbtUTG7ODtYiGjGwy0tAn5bkugx5L5nyjS9cf/5Zteuh/U+zm61S9Xy1WwMv/Ha2BCWF2l5pMaUNd/CtlCEMwz6GVTiACWPEJZmsXBN2RWEARJxebVGVWLVxJ+kBzxCKvfYhoFAihuRo=
